const API='https://www.recipetineats.com/wp-json/wp/v2/posts';
const $=s=>document.querySelector(s); let recipes=[], filtered=[], selected=new Set();
const prefs=JSON.parse(localStorage.getItem('rtePrefs')||'{}');
const savePrefs=()=>localStorage.setItem('rtePrefs',JSON.stringify(prefs));
function text(html=''){const d=document.createElement('div');d.innerHTML=html;return d.textContent.trim()}
function mins(v){if(!v)return null;if(typeof v==='number')return v;let m=String(v).match(/PT(?:(\d+)H)?(?:(\d+)M)?/i);if(m)return (+m[1]||0)*60+(+m[2]||0);m=String(v).match(/(\d+)/);return m?+m[1]:null}
function arr(v){return Array.isArray(v)?v:v?[v]:[]}
function protein(title,ings=[]){let s=(title+' '+ings.join(' ')).toLowerCase();for(const [k,v] of [['Chicken','chicken'],['Beef','beef'],['Pork','pork|bacon|ham|sausage'],['Lamb','lamb'],['Salmon','salmon'],['Shrimp','shrimp|prawn'],['Fish','fish|cod|tuna|barramundi'],['Seafood','mussel|squid|seafood|crab']])if(new RegExp(v).test(s))return k;if(/tofu|eggplant|vegetable|vegetarian|mushroom|cauliflower|broccoli/.test(s))return 'Vegetarian';return ''}
function parseRecipe(post){let html=post.content?.rendered||'', schema=null;const doc=new DOMParser().parseFromString(html,'text/html');
 for(const sc of doc.querySelectorAll('script[type="application/ld+json"]')){try{let x=JSON.parse(sc.textContent);let all=Array.isArray(x)?x:(x['@graph']||[x]);schema=all.find(z=>arr(z['@type']).includes('Recipe'));if(schema)break}catch(e){}}
 let ingredients=arr(schema?.recipeIngredient).map(text); if(!ingredients.length) ingredients=[...doc.querySelectorAll('.wprm-recipe-ingredient')].map(x=>x.textContent.trim()).filter(Boolean);
 let nutrition=schema?.nutrition||{};let image=schema?.image; if(Array.isArray(image))image=image[0]; if(image&&typeof image==='object')image=image.url; image=image||post._embedded?.['wp:featuredmedia']?.[0]?.source_url||'';
 let title=text(schema?.name||post.title?.rendered||'Untitled');let prep=mins(schema?.prepTime)||mins(doc.querySelector('.wprm-recipe-prep_time-minutes')?.textContent);let cook=mins(schema?.cookTime)||mins(doc.querySelector('.wprm-recipe-cook_time-minutes')?.textContent);
 let cats=(post._embedded?.['wp:term']||[]).flat().map(x=>x.name).filter(Boolean);
 return {id:'web-'+post.id,title,url:post.link,source:'web',image,ingredients,ingredientCount:ingredients.length,prep,cook,total:mins(schema?.totalTime),servings:text(schema?.recipeYield||''),cuisine:arr(schema?.recipeCuisine).join(', '),category:arr(schema?.recipeCategory).join(', ')||cats.join(', '),protein:protein(title,ingredients),nutrition:{calories:text(nutrition.calories||''),protein:text(nutrition.proteinContent||''),carbs:text(nutrition.carbohydrateContent||''),fat:text(nutrition.fatContent||''),sodium:text(nutrition.sodiumContent||'')},date:post.date};}
async function loadCookbook(){let r=await fetch('cookbook.json');return (await r.json()).map(x=>({...x,protein:protein(x.title),ingredients:[],ingredientCount:null,prep:null,cook:null,image:'',category:x.section,nutrition:{}}))}
async function sync(){try{$('#status').textContent='Syncing public RecipeTin Eats recipes…';let web=[],page=1,total=1;do{let u=`${API}?per_page=100&page=${page}&_embed=1`;let r=await fetch(u);if(!r.ok)throw Error(`Website API ${r.status}`);total=+r.headers.get('X-WP-TotalPages')||page;let posts=await r.json();for(const p of posts){let rec=parseRecipe(p);if(rec.ingredients.length||/recipe/i.test(p.content?.rendered||''))web.push(rec)}$('#status').textContent=`Downloaded page ${page} of ${total} — ${web.length} recipes found`;page++}while(page<=total);
 let books=await loadCookbook();let byTitle=new Map(web.map(x=>[x.title.toLowerCase(),x]));for(const b of books){let w=byTitle.get(b.title.toLowerCase());if(w){w.bookPage=b.page;w.bookSection=b.section;w.exclusive=b.exclusive}else web.push(b)}recipes=web;localStorage.setItem('rteRecipeDb',JSON.stringify(recipes));localStorage.setItem('rteLastSync',new Date().toISOString());$('#status').textContent=`Ready: ${recipes.length} recipes. Synced ${new Date().toLocaleString()}.`;apply()}catch(e){$('#status').textContent='Sync failed: '+e.message+' — using saved cookbook/database.';if(!recipes.length){recipes=await loadCookbook();apply()}}}
async function init(){try{recipes=JSON.parse(localStorage.getItem('rteRecipeDb')||'[]')}catch{}if(!recipes.length)recipes=await loadCookbook();let d=localStorage.getItem('rteLastSync');$('#status').textContent=d?`Using ${recipes.length} saved recipes. Last synced ${new Date(d).toLocaleString()}.`:`${recipes.length} cookbook entries loaded. Tap Sync recipes to download the website catalogue.`;apply();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
function apply(){let q=$('#search').value.toLowerCase(),src=$('#source').value,p=$('#protein').value,ic=$('#ingredientCount').value,prep=+$('select#prep').value,cook=+$('select#cook').value,rat=+$('select#rating').value;
 filtered=recipes.filter(r=>{let pref=prefs[r.id]||{};let hay=[r.title,r.category,r.cuisine,r.protein,...(r.ingredients||[])].join(' ').toLowerCase();if(q&&!hay.includes(q))return false;if(src==='web'&&r.source!=='web')return false;if(src==='cookbook'&&!r.bookPage&&!r.page)return false;if(src==='favorites'&&!pref.favorite)return false;if(p&&r.protein!==p)return false;if(ic){if(r.ingredientCount==null)return false;if(ic==='2'||ic==='3'){if(r.ingredientCount!==+ic)return false}else if(r.ingredientCount>+ic)return false}if(prep&&(r.prep==null||r.prep>prep))return false;if(cook&&(r.cook==null||r.cook>cook))return false;if(rat&&(pref.rating||0)<rat)return false;return true});render()}
function render(){ $('#count').textContent=filtered.length;$('#cards').innerHTML=filtered.map(r=>{let pr=prefs[r.id]||{};return `<article class="card ${selected.has(r.id)?'selected':''}" data-id="${r.id}">${r.image?`<img class="photo" loading="lazy" src="${r.image}" alt="">`:`<div class="photo placeholder">🍲</div>`}<div class="body"><h3>${r.title}</h3><div class="meta">${r.protein?`<span class="pill">${r.protein}</span>`:''}${r.prep!=null?`<span class="pill">Prep ${r.prep}m</span>`:''}${r.cook!=null?`<span class="pill">Cook ${r.cook}m</span>`:''}${r.ingredientCount!=null?`<span class="pill">${r.ingredientCount} ingredients</span>`:''}${r.bookPage||r.page?`<span class="pill">Book p. ${r.bookPage||r.page}</span>`:''}</div><div class="tags">${r.category||''}</div><div class="card-actions"><button class="heart ${pr.favorite?'active':''}" data-fav>${pr.favorite?'♥':'♡'}</button><button data-select>${selected.has(r.id)?'Selected':'Shop'}</button><button data-open>Details</button></div></div></article>`}).join('');$('#selectedCount').textContent=selected.size}
$('#cards').onclick=e=>{let card=e.target.closest('.card');if(!card)return;let r=recipes.find(x=>x.id===card.dataset.id);if(e.target.closest('[data-fav]')){prefs[r.id]=prefs[r.id]||{};prefs[r.id].favorite=!prefs[r.id].favorite;savePrefs();apply()}else if(e.target.closest('[data-select]')){selected.has(r.id)?selected.delete(r.id):selected.add(r.id);render()}else if(e.target.closest('[data-open]'))openDetail(r)};
function openDetail(r){let pr=prefs[r.id]||{};$('#detailBody').innerHTML=`${r.image?`<img class="detail-photo" src="${r.image}">`:''}<h2>${r.title}</h2><p>${r.category||''}${r.cuisine?' · '+r.cuisine:''}</p><p><b>Prep:</b> ${r.prep??'—'} min · <b>Cook:</b> ${r.cook??'—'} min · <b>Ingredients:</b> ${r.ingredientCount??'—'}${r.bookPage||r.page?` · <b>Cookbook page:</b> ${r.bookPage||r.page}`:''}</p><h3>Nutrition per serving</h3><p>Calories ${r.nutrition?.calories||'—'} · Protein ${r.nutrition?.protein||'—'} · Carbs ${r.nutrition?.carbs||'—'} · Fat ${r.nutrition?.fat||'—'} · Sodium ${r.nutrition?.sodium||'—'}</p>${r.ingredients?.length?`<h3>Ingredients</h3><ul class="ingredients">${r.ingredients.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>Ingredients are available on the official page or in your cookbook.</p>'}<p><a target="_blank" rel="noopener" href="${r.url||'https://www.google.com/search?q='+encodeURIComponent(r.title+' RecipeTin Eats')}">Open official recipe</a> · <a target="_blank" rel="noopener" href="https://www.google.com/search?tbm=isch&q=${encodeURIComponent(r.title+' RecipeTin Eats')}">Google food photos</a></p><h3>My rating</h3><div class="rating">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button data-rate="${n}">${n}</button>`).join('')} <b>${pr.rating||'Not rated'}</b></div><h3>My notes</h3><textarea id="note" rows="5" style="width:100%">${pr.notes||''}</textarea><p><button id="saveNote">Save notes</button> <button id="shareRecipe">Share recipe</button></p>`;$('#detail').showModal();document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{prefs[r.id]=prefs[r.id]||{};prefs[r.id].rating=+b.dataset.rate;savePrefs();openDetail(r)});$('#saveNote').onclick=()=>{prefs[r.id]=prefs[r.id]||{};prefs[r.id].notes=$('#note').value;savePrefs();alert('Saved')};$('#shareRecipe').onclick=()=>navigator.share?.({title:r.title,text:`${r.title}${r.bookPage?' — Dinner p. '+r.bookPage:''}`,url:r.url||location.href})}
function shopping(){let chosen=recipes.filter(r=>selected.has(r.id)),items=chosen.flatMap(r=>(r.ingredients||[]).map(x=>({recipe:r.title,item:x})));$('#shoppingBody').innerHTML=items.length?`<ul>${items.map(x=>`<li><label><input type="checkbox"> ${x.item} <small>(${x.recipe})</small></label></li>`).join('')}</ul>`:`<p>The selected recipes do not yet have public ingredient data. Open the official pages or sync again. Cookbook-exclusive ingredients require transcription from the book photos.</p>`;$('#shopping').showModal()}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());$('#syncBtn').onclick=sync;$('#shoppingBtn').onclick=shopping;$('#randomBtn').onclick=()=>{if(!filtered.length)return alert('No matching recipes');openDetail(filtered[Math.floor(Math.random()*filtered.length)])};['search','source','protein','ingredientCount','prep','cook','rating'].forEach(id=>$('#'+id).oninput=apply);$('#printShop').onclick=()=>print();$('#shareShop').onclick=()=>{let t=[...$('#shoppingBody').querySelectorAll('li')].map(x=>x.textContent.trim()).join('\n');navigator.share?.({title:'Shopping list',text:t})};init();
